### ISSUE TITLE
peerjs fails to build on Xenial arm64

### ISSUE THREAD

**Issue by tfoote** [easymov/ros_peerjs-release#1]
http://build.ros.org/job/Kbin_uxv8_uXv8__ros_peerjs__ubuntu_xenial_arm64__binary/219/console

It appears to be a dependency issue with electron being unavilable. If this is not resolvable we can blacklist the package so it stops trying to build.

```
00:29:19.956 npm WARN peer_bridge.js@1.0.0 No description
00:29:20.047 npm WARN peer_bridge.js@1.0.0 No repository field.
00:29:20.060 npm WARN peer_bridge.js@1.0.0 license should be a valid SPDX license expression
00:29:20.181 npm ERR! Linux 4.4.0-93-generic
00:29:20.184 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
00:29:20.186 npm ERR! node v4.2.6
00:29:20.188 npm ERR! npm  v3.5.2
00:29:20.191 npm ERR! code ELIFECYCLE
00:29:20.192 
00:29:20.194 npm ERR! electron@1.7.9 postinstall: `node install.js`
00:29:20.195 npm ERR! Exit status 1
00:29:20.197 npm ERR! 
00:29:20.198 npm ERR! Failed at the electron@1.7.9 postinstall script 'node install.js'.
00:29:20.200 npm ERR! Make sure you have the latest version of node.js and npm installed.
00:29:20.201 npm ERR! If you do, this is most likely a problem with the electron package,
00:29:20.202 npm ERR! not with npm itself.
00:29:20.203 npm ERR! Tell the author that this fails on your system:
00:29:20.204 npm ERR!     node install.js
00:29:20.205 npm ERR! You can get information on how to open an issue for this project with:
00:29:20.206 npm ERR!     npm bugs electron
00:29:20.207 npm ERR! Or if that isn't available, you can get their info via:
00:29:20.209 npm ERR!     npm owner ls electron
00:29:20.210 npm ERR! There is likely additional logging output above.
00:29:20.857 
00:29:20.859 npm ERR! Please include the following file with any support request:
00:29:20.860 npm ERR!     /tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8/npm-debug.log
00:29:20.892 CMakeFiles/node_modules.dir/build.make:60: recipe for target 'node_modules' failed
00:29:20.893 make[4]: *** [node_modules] Error 1
00:29:20.893 make[4]: Leaving directory '/tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8/obj-aarch64-linux-gnu'
00:29:20.895 CMakeFiles/Makefile2:262: recipe for target 'CMakeFiles/node_modules.dir/all' failed
00:29:20.895 make[3]: *** [CMakeFiles/node_modules.dir/all] Error 2
00:29:20.897 make[3]: Leaving directory '/tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8/obj-aarch64-linux-gnu'
00:29:20.899 Makefile:130: recipe for target 'all' failed
00:29:20.899 make[2]: *** [all] Error 2
00:29:20.900 make[2]: Leaving directory '/tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8/obj-aarch64-linux-gnu'
00:29:20.904 dh_auto_build: make -j1 returned exit code 2
00:29:20.904 	cd /tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8
00:29:20.910 debian/rules:36: recipe for target 'override_dh_auto_build' failed
00:29:20.911 make[1]: *** [override_dh_auto_build] Error 2
00:29:20.911 make[1]: Leaving directory '/tmp/binarydeb/ros-kinetic-ros-peerjs-0.1.8'
00:29:20.926 debian/rules:23: recipe for target 'build' failed
00:29:20.926 make: *** [build] Error 2
00:29:20.929 dpkg-buildpackage: error: debian/rules build gave error exit status 2
00:29:20.940 E: Building failed
00:29:20.967 Traceback (most recent call last):
00:29:20.968   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
00:29:20.968     subprocess.check_call(cmd, cwd=source_dir)
00:29:20.968   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
00:29:20.968     raise CalledProcessError(retcode, cmd)
00:29:20.968 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-kinetic-ros-peerjs']' returned non-zero exit status 1
00:29:20.969 # END SUBSECTION
```

**Comment by lelongg** [comment]
Don't know how to fix it yet. So yes, it would be better to blacklist it for now.

**Comment by tfoote** [comment]
Blacklist PR: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/99

With this cross referenced you can close this if you want.
